[package]
name = "krpc"
version = "0.1.0"
edition = "2021"
authors = [ "Mike Bernard" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[dependencies]

[dev-dependencies]
claim = "0.5"